In [3]:
import numpy as np
arr1 = np.array([[0, 1, 2, 3],[4, 5, 6, 7,],[8, 9, 10, 11]])
print(arr1)
print(f"Hàng 2: {arr1[1]}")
print(f"Cột 3: {arr1[:, 2]}")
print(f"Submatrix" f"hàng 1-2, cột 1-2:\n{arr1[1:3, 1:3]}")
dtype_float = np.float64
print(f"dtype_float = {dtype_float}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Hàng 2: [4 5 6 7]
Cột 3: [ 2  6 10]
Submatrixhàng 1-2, cột 1-2:
[[ 5  6]
 [ 9 10]]
dtype_float = <class 'numpy.float64'>
