In [1]:
import numpy as np
np.random.seed(42)
A = np.array([[5, 6, 8],
              [7, 2, 4],
              [1, 6, 3]])

print(A)
B = np.array([10, 20, 30])
print(B)
result_add = A + B
print("Kết quả phép cộng A + B:")
print(result_add)

result_sub = A - B
print("Kết quả phép trừ A - B:")
print(result_sub)

[[5 6 8]
 [7 2 4]
 [1 6 3]]
[10 20 30]
Kết quả phép cộng A + B:
[[15 26 38]
 [17 22 34]
 [11 26 33]]
Kết quả phép trừ A - B:
[[ -5 -14 -22]
 [ -3 -18 -26]
 [ -9 -14 -27]]
